
    create table pix_gerados (
        id bigint generated by default as identity,
        pixcode varchar(255),
        qr_code_base64 text,
        primary key (id)
    );

    alter table if exists pix_gerados 
       add column chave_pix varchar(255);

    alter table if exists pix_gerados 
       add column cidade_beneficiario varchar(255);

    alter table if exists pix_gerados 
       add column codigo_transferencia varchar(255);

    alter table if exists pix_gerados 
       add column data_geracao timestamp(6);

    alter table if exists pix_gerados 
       add column nome_beneficiario varchar(255);

    alter table if exists pix_gerados 
       alter column qr_code_base64 set data type varchar(2048);

    alter table if exists pix_gerados 
       add column valor float(53);
